import { SiteConfig } from './gsheet';

/**
 * Offline fallback content.
 *
 * This is a frozen snapshot of the real, live Google Sheet content as it stood
 * on 2026-07-08 (July 8, 2026). When Google Sheets is unreachable (network
 * error, sheet deleted/unpublished, etc.), src/lib/server-data.ts serves these
 * values so visitors see the last-known real content instead of blank sections.
 *
 * The object/array shapes here MUST match exactly what the row mappers in
 * src/lib/server-data.ts produce (same field names). This file was generated by
 * running those exact mappers over the CSV exports in
 * assets/sheets/*_2026-07-08.csv. To refresh it, re-export the sheets and
 * regenerate. Do NOT hand-edit field names out of sync with the mappers.
 *
 * PERSONAL DATA IS DELIBERATELY STRIPPED FROM THIS SNAPSHOT and must stay
 * stripped after any regeneration: the repo is public and a committed copy of
 * the sheet does not rotate when the sheet does. Removed keys:
 * members_contacts, taxi_contacts, contact_phone; and every per-event
 * coordinator/contact value is blanked. Every consumer already guards for the
 * absence (Footer memberContacts.length > 0, Stay hospitalityContact &&,
 * Maps parsedTaxiContacts.length > 0), and this data only ever renders when
 * the live sheet is unreachable.
 */

// Config snapshot (key -> value pairs, same shape fetchSiteConfig returns).
export const FALLBACK_CONFIG: SiteConfig = {
  "logo_url": "https://drive.google.com/file/d/1aIR3Y9QXJZ8E8eG2rquYECnUoL07Mxsz/view?usp=sharing",
  "background_image_url": "https://drive.google.com/file/d/1ALCRVrYGO9tyG0m834ckoaEtMmueIqcc/view?usp=sharing",
  "hero_year": "2026",
  "hero_subtitle": "Experience The Metamorphosis",
  "hero_date": "2026-02-27",
  "about_title": "Nisadya '26",
  "about_subtitle": "",
  "about_description": "",
  "about_description_alignment": "center",
  "about_tagline": "",
  "doms_title": "",
  "doms_subtitle": "",
  "doms_description": "Since its inception in 1978, the Department of Management Studies at NIT Trichy (DoMS-NITT) has been a nexus of innovation and leadership, shaping the future of management professionals in India. As a department, under the Ministry of Education, DoMS-NITT merges academic excellence with cutting-edge research to contribute to the nation's progress. It is set apart by its vibrant industry ties and an alumni network that continues to fuel growth through mentorship, offering students boundless learning opportunities and a roadmap to career success.",
  "doms_description_alignment": "center",
  "doms_tagline": "",
  "contact_email": "nisadya@nitt.edu",
  "hero_description": "Unleash your potential at the biggest cultural and technical extravaganza of the year. Join us for 2 days of innovation, creativity, and fun.",
  "contact_linkedin": "https://www.linkedin.com/company/nisadya2024/",
  "contact_instagram": "https://www.instagram.com/nisadya.nitt/",
  "contact_twitter": "",
  "contact_youtube": "",
  "contact_location": "National Institute of Technology,\nTanjore Main Road, NH 83,\nTiruchirappalli - 620015, Tamil Nadu, India",
  "registration_start_date": "2026-01-30",
  "registration_end_date": "",
  "favicon_url": "https://drive.google.com/file/d/1tfhv7dbAnjSHcKTldT19Ts1j3jOv3jQo/view?usp=sharing",
  "unstop_url": "https://unstop.com/college-fests/nisadya-department-of-management-studies-national-institute-of-technology-trichy-434644"
};

// Events snapshot (matches the events rowMapper in server-data.ts).
export const FALLBACK_EVENTS = [
  {
    "name": "Marketing Event – MERX",
    "description": "MERX is a marketing-focused competitive event that assesses participants comprehension of fundamental marketing concepts as well as their capacity for creativity, critical thought, and strategic decision-making. Through quizzes, campaign development, and case-based problem solving, the event challenges participants by fusing theory with practical application",
    "startDate": "27/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/MdNY4bP?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1127HjHbF0J3K27on94iT-S0Afc8XDVPD/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Strategy Event – STRATEGY SPRINT",
    "description": "Strategy Sprint is a high-intensity, consulting-style strategy competition designed to test participants on strategic thinking, business judgment, financial logic, and executive decision-making under uncertainty. The event simulates real-world boardroom environments where clarity, conviction, and adaptability define winning strategies.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/RdLzf9t?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1uv7-ZV50ceN_3KGhNLjyzQ4ofcBerabu/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Operations Event – PRAXIS",
    "description": "The event aims to provide a structured platform focusing on practical application of operations concepts rather than only theoretical knowledge. The competition is designed to simulate real-world operational challenges faced by managers in manufacturing and service organizations. Praxis gives you an opportunity to hone your abilities to solve the operational puzzles.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/DfJCs4u?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/14yF6S-4gaP8m_cCie51T0hoDqkqacBXn/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "HR Event - PRAVARAN",
    "description": "This event takes participants through a journey of HR fundamentals, practical case analysis, and live negotiation challenges, simulating situations faced by HR professionals in today’s dynamic organizations. Each round pushes you to think sharper, communicate better, and act smarter.",
    "startDate": "27/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/oZUizBv?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1UBJDisOAsQv6jgJODrX5zSd7DCCVIbqz/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Finance Event – VRIDDHI",
    "description": "Vriddhi - Finance Event aims to evaluate participants financial reasoning, analytical ability, and decision-making skills through progressively challenging rounds, moving from conceptual understanding to applied financial analysis under constraints.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/AyYVx1r?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/116yJvQHbgR1IEyiSV6O1QDWjPiOKeeuh/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "IPL Auction Event - BIDSTORM",
    "description": "This event takes participants through the thrilling world of an IPL-style player auction, where analytical skills meet real-time decision-making. From understanding player statistics and team combinations to smart bidding and tactical negotiations, each round simulates the intensity of an actual IPL auction table. Every stage challenges you to think fast, bid smart, manage budgets effectively, and outplay rival teams to create the ultimate squad.",
    "startDate": "27/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/LkHvmaR?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1ow1HiI0E0M-PIAEuBkbx5I44Sct8sjlk/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Business Quiz - UTTAR",
    "description": "B-QuizArena is an engaging business quiz competition that evaluates participants on business fundamentals, current affairs, brand awareness, and rapid decision-making.\nThe event follows a progressive elimination format, where each round increases in difficulty, ensuring an exciting and competitive experience.\nThe event is open to undergraduate and postgraduate students from all academic streams.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/si2yF70?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/13i4FC6ydTJsDIC5w9qdxn96vd0mBKuZO/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Business Charades - MANIFEST",
    "description": "Business Charades is a multi-round management event designed to assess participants’ understanding of business fundamentals, corporate language, brand awareness, and strategic thinking through expressive and interactive rounds.\nThe event follows a progressive round-based structure, with each round increasing in complexity and depth, ensuring a competitive and entertaining experience for MBA students.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/owD1H8y?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1oGmcUhfixPbW3SxREoyCFlB0gPbU411m/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Chanakya -  The ULTIMATE MANAGER",
    "description": "This competition is designed to assess participants on their overall managerial aptitude, decision-making ability, problem-solving skills, and business awareness. The event provides a dynamic platform for participants to demonstrate their competence under time-bound conditions.\nThe competition will be conducted entirely in offline mode. The structure and format of the competition will progress across multiple rounds, with further details communicated during the event.",
    "startDate": "27/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/mDrIwEX?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1_yI97z7OBpEpvND-6YWZDseK4a55K7d5/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  },
  {
    "name": "Business Plan – SANKALP",
    "description": "Sankalp – The Entrepreneurship Event is a premier business plan competition conducted as part of Nisadya 2026, the annual business fest of the Department of Management Studies, NIT Tiruchirappalli. The event provides a dynamic platform for aspiring entrepreneurs to transform innovative ideas into structured, practical, and scalable business models. Sankalp challenges participants to think strategically, identify real-world problems, analyze market opportunities, and present viable solutions through a competitive pitching process. Designed to nurture entrepreneurial thinking, leadership, and decision-making skills, the event bridges the gap between classroom learning and real business execution, empowering students to take their first confident step into the world of entrepreneurship.",
    "startDate": "28/2/2026",
    "endDate": "28/2/2026",
    "unstopLink": "https://unstop.com/o/npEOAZu?lb=1LtEUIVe&utm_medium=Share&utm_source=lykwimpo42986&utm_campaign=Competitions",
    "imageLink": "https://drive.google.com/file/d/1EfXnHRbv-qzunWG1-jm9plSRH3GtxcZb/view?usp=drive_link",
    "coordinator": "",
    "contact": "",
    "category": ""
  }
];

// Schedule snapshot (matches the schedule rowMapper in server-data.ts).
export const FALLBACK_SCHEDULE = [
  {
    "day": "1",
    "date": "",
    "time": "9:00 AM - 10: 00 AM",
    "title": "Event inaguration",
    "venue": "EEE auditorium",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "10.30AM - 1:30PM",
    "title": "Marketing Event – MERX",
    "venue": "Intro at LH4\nConference Hall(P) + LH5",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "10.45AM - 1:45PM",
    "title": "HR Event -PRAVARAN",
    "venue": "LH1",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "2:30PM - 5:30PM",
    "title": "Finance Event – VRIDDHI",
    "venue": "LH1 + Conference(P) + LH5",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "2:45PM - 3:30PM",
    "title": "Best Manager (1) – CHANAKYA",
    "venue": "LH2",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "3:00PM - 5:00 PM",
    "title": "Business Quiz – UTTAR",
    "venue": "LH4",
    "category": ""
  },
  {
    "day": "1",
    "date": "",
    "time": "5:00 PM - 7:00PM",
    "title": "IPL Auction (1)",
    "venue": "LH1",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "9:00AM - 12:00PM",
    "title": "Consulting Event -STRATEGY SPRINT",
    "venue": "Intro at LH1 Conference Hall(P) + LH5",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "9:30AM - 12:30PM",
    "title": "Operations Event - PRAXIS",
    "venue": "LH4",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "1:00PM - 4:00PM",
    "title": "Business Plan – SANKALP",
    "venue": "LH1+Conference(P) +LH5",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "1:30PM - 4:00 PM",
    "title": "Best Manager (2) – CHANAKYA",
    "venue": "LH2",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "1:45PM - 4:45 PM",
    "title": "IPL Auction (2)",
    "venue": "LH1",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "2:30PM - 4:45PM",
    "title": "Business Charades – MANIFEST",
    "venue": "LH4",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "5:00PM - 5:45 PM",
    "title": "Best Manager (F) – CHANAKYA",
    "venue": "",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "5:45PM - 6:30 PM",
    "title": "VALEDICTORY",
    "venue": "",
    "category": ""
  },
  {
    "day": "2",
    "date": "",
    "time": "6:30PM - 8:00PM",
    "title": "PRO SHOW",
    "venue": "",
    "category": ""
  }
];
